name: Pukánszky Péter # kulcs-érték párok
age: 22
details: semmi # beágyazott kollekció
givenname: Péter
familyname: Pukánszky
birthyear: 1998
languages: # értékek listája (tömb)
- Hungarian
- English
- German